/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cG44VW7wJop
 */
import {
  SelectValue,
  SelectTrigger,
  SelectLabel,
  SelectItem,
  SelectGroup,
  SelectContent,
  Select,
} from "@/components/ui/select";

export default function Dashboard() {
  return (
    <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6 bg-gray-900 dark:bg-black">
      <div className="flex items-center">
        <Select>
          <SelectTrigger className="ml-auto w-[200px]">
            <SelectValue placeholder="Select Time Period" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Time Period</SelectLabel>
              <SelectItem value="day">Day</SelectItem>
              <SelectItem value="week">Week</SelectItem>
              <SelectItem value="month">Month</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
        <Select>
          <SelectTrigger className="ml-4 w-[200px]">
            <SelectValue placeholder="Select Graph" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Graph</SelectLabel>
              <SelectItem value="overall">
                Overall Energy Consumption
              </SelectItem>
              <SelectItem value="device-wise">
                Device-wise Energy Consumption
              </SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
      </div>
      <div className="border shadow-sm rounded-lg hidden" id="overall-graph">
        <img
          alt="Energy Consumption Graph"
          className="w-full object-cover"
          height="300"
          src="/placeholder.svg"
          style={{
            aspectRatio: "500/300",
            objectFit: "cover",
          }}
          width="500"
        />
        <div className="p-4">
          <h2 className="font-semibold text-lg">Overall Energy Consumption</h2>
        </div>
      </div>
      <div
        className="border shadow-sm rounded-lg hidden"
        id="device-wise-graph"
      >
        <img
          alt="Device Energy Consumption Graph"
          className="w-full object-cover"
          height="300"
          src="/placeholder.svg"
          style={{
            aspectRatio: "500/300",
            objectFit: "cover",
          }}
          width="500"
        />
        <div className="p-4">
          <h2 className="font-semibold text-lg">
            Device-wise Energy Consumption
          </h2>
        </div>
      </div>
    </main>
  );
}
